services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pokermon_network

  redis:
    container_name: redis_cache
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - pokermon_network

  quarkus:
    image: kauanmatheusoliveira/pokermon:0.4.0
#    build:
#      context: .
#      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: quarkus_app
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EXTERNAL_API_KEY: ${EXTERNAL_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - pokermon_network

volumes:
  pgdata:

networks:
  pokermon_network: