name: Build and Deploy (Split)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.DOCKERHUB_USERNAME }}/pokermon:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokermon:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Create .env file
        run: |
          cat <<EOF > /home/ubuntu/TCG.Pokermon/.env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Create publicKey.pem file
        run: |
          cat <<EOF > /home/ubuntu/TCG.Pokermon/src/main/resources/META-INF/resources/publicKey.pem
          ${{ secrets.JWT_PUBLIC_KEY }}
          EOF

      - name: Create privateKey.pem file
        run: |
          cat <<EOF > /home/ubuntu/TCG.Pokermon/src/main/resources/META-INF/resources/privateKey.pem
          ${{ secrets.JWT_PRIVATE_KEY }}
          EOF

      - name: Pull and restart container
        run: |
          cd /home/ubuntu/TCG.Pokermon
          docker-compose pull
          docker-compose up -d
